arch:
- aarch64
- amd64
- armhf
- armv7
- i386
codenotary: hassadons@simecek.eu
description: Bigclown Gateway from Hardwario Hassio add-on by DSCK
init: false
name: Bigclown GW
devices:
  - "/dev/ttyUSB0"
options:
  mqtt_host: "core-mosquitto"
  mqtt_host_port: 1883
  mqtt_username: "bcg"
  mqtt_password: "hardwario"
  usb_port: "/dev/ttyUSB0"
  debug: false
schema:
  mqtt_host: str
  mqtt_host_port: int
  mqtt_username: str
  mqtt_password: str
  usb_port: str
  debug: bool
slug: bigclowngw
url: https://github.com/dansck/hassio-addons/tree/main/bigclowngw
version: 1.0.0
